### ISSUE TITLE
Norton treating as Virus

### ISSUE THREAD

**Issue by krishnaraovs** [movAX13h/P8Coder#2]
Norton scan treating the file as virus
Threate Name: Ws.Reputation.1
https://us.norton.com/security_response/writeup.jsp?docid=2010-051308-1854-99

**Comment by movAX13h** [comment]
I scanned it with several scanners and uploaded it to online virus scanner services but none found anything critical. Feel free to look into the source or try to compile it yourself.

**Comment by krishnaraovs** [comment]
This doesn't happened with v1.0, however its considered not big threat. I will use it and try to compile.
