### ISSUE TITLE
Enhancement: Default Cart

### ISSUE THREAD

**Issue by krishnaraovs** [movAX13h/P8Coder#3]
If there was any cart available the program is throwing error as 
"No cartridge selected. Code copied to clipboard"

Instead of this if its '"New then create a default cart template and select it automatically, because if we selected any existing cartridge its getting overwritten by this new code.

**Comment by movAX13h** [comment]
Thanks! I will look into this issue soon.

**Comment by movAX13h** [comment]
I think it's fine as it is. I'm starting my projects in pico-8 with graphics and save the cart and then select it in P8Coder if I want to make a game using the cart.

I dont want to deliver the application with a default cart because that's pico-8 business.

**Comment by krishnaraovs** [comment]
For the newbies (like me) it will be a good help. rather than doing all that process. Additionally if you have time take a look into this.

when we click "Build & Run"pico-8 instance starts but after editing the code (without closing earlier pico-8 instance) and again clicked on "Build & Run" no effect is happening, it would be better to start another instance with the newly modified code as pico-8 allows multiple instances.

**Comment by movAX13h** [comment]
I've just released v1.1. It creates a new pico-8 instance everytime now and has a new dialog for launch settings.
