### ISSUE TITLE
Error when trying to load cartridge

### ISSUE THREAD

**Issue by fiedldi** [movAX13h/P8Coder#7]
Hi movAX13h,

and thanks for coding the P8Coder! At the moment I'm trying to get back into the coding world (last time I was coding it was on the C64 25 years ago) so P8Coder will surely be of help.

Anyways, when I'm trying to load a cartridge to my project, a "Failed to load the cartridge!" error appears. Any guess what it is I'm doing wrong?

Thanks in advance,
fiedldi

**Comment by movAX13h** [comment]
Hi fiedldi,

are you loading a p8 file or a png cartridge? P8Coder only works with P8 files. I can take a look at what's  happening if you like (upload here or send to movAX13h@thrill-project.com). 

If you are familiar with Visual Studio, you could run P8Coder from source code and set some breakpoints to find out why it fails to load.

greets,
mov

**Comment by fiedldi** [comment]
Hi movAX13h,

yes, I'm loading a p8 file I created with PICO-8  0.1.11g. It contains just one line of code for testing purposes. 

Here are the .p8 and .p8c files:
[test.zip](https://github.com/movAX13h/P8Coder/files/1977784/test.zip)

Thanks for looking into it.

Greetings,
fiedldi

**Comment by movAX13h** [comment]
Ok, I just noticed that since v0.1.11e pico-8 does not write empty sections to the cart file anymore.

I will update P8Coder tonight.

Thanks for reporting!

**Comment by movAX13h** [comment]
Fixed it.
https://github.com/movAX13h/P8Coder/releases/tag/1.4
