### ISSUE TITLE
Multi-line comments recognised unintentionally

### ISSUE THREAD

**Issue by cpuSonicatt** [movAX13h/P8Coder#8]
When nesting tables (or in a case where you use two square brackets `[...[...]]` ), P8Coder recognises this as a multi-line comment and formats the code accordingly. For example:

![image](https://user-images.githubusercontent.com/18102974/85376476-ac7a2d80-b52f-11ea-9696-5ccfed3e76a9.png)

**Comment by movAX13h** [comment]
Thank you for reporting. I'll try to fix it tonight.

**Comment by movAX13h** [comment]
Problem solved. Download link is updated.
